import os
from flask import Flask, jsonify, render_template, send_from_directory, current_app
from flask_migrate import Migrate
from flask_jwt_extended import JWTManager
from flask_cors import CORS
from dotenv import load_dotenv
from config import config
from app.utils.extensions import db, ma, mail, mongo  # Centralized extension objects
from app.routes.habit_routes import habit_bp
from app.routes.auth_routes import auth_bp
from app.models.models import Habit  # Import the Habit model

# Load environment variables
load_dotenv()

# Initialize extensions
jwt = JWTManager()
migrate = Migrate()

# Global error handlers
def register_error_handlers(app):
    @app.errorhandler(404)
    def not_found(error):
        return jsonify({"message": "Resource not found"}), 404

    @app.errorhandler(500)
    def internal_error(error):
        return jsonify({"message": "Internal server error"}), 500

def create_app(config_class=None):
    app = Flask(__name__)

    # Allow frontend (React) to communicate with backend
    CORS(app, origins=[os.getenv("FRONTEND_URL", "http://localhost:3000")])

    # Load config based on environment
    env = os.getenv('FLASK_ENV', 'development')
    app.config.from_object(config.get(env, config['development']))

    # Override DB URL from environment if provided
    db_url = os.getenv("DATABASE_URL")
    if db_url:
        app.config['SQLALCHEMY_DATABASE_URI'] = db_url
    elif not app.config.get("SQLALCHEMY_DATABASE_URI"):
        raise ValueError("DATABASE_URL is not set in the environment variables.")
    
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['JWT_SECRET_KEY'] = os.getenv("JWT_SECRET_KEY", "super-secret-key")

    # Initialize extensions
    db.init_app(app)
    ma.init_app(app)
    migrate.init_app(app, db)
    jwt.init_app(app)
    mail.init_app(app)

    # MongoDB setup
    app.config["MONGO_URI"] = os.getenv("MONGO_PROD_URI")
    mongo.init_app(app)

    # Register blueprints (routes)
    app.register_blueprint(habit_bp, url_prefix="/api/habits")
    app.register_blueprint(auth_bp, url_prefix="/api/auth")

    # Register global error handlers
    register_error_handlers(app)

    # API Test Endpoint
    @app.route('/api/data')
    def get_data():
        return jsonify({"message": "Hello from Flask!"})

    # Example of returning dynamic HTML content
    @app.route('/api/get_html')
    def get_html():
        dynamic_html = """
        <div>
            <h2>Dynamic Content from Flask</h2>
            <p>This content is generated by the backend (Flask) and displayed in the frontend (React).</p>
        </div>
        """
        return jsonify({"html": dynamic_html})

    # Route to fetch habits from database
    @app.route('/fetch_habits')
    def fetch_habits():
        try:
            habits = Habit.query.filter_by(deleted_at=None).all()
            if not habits:
                return jsonify({"message": "No habits found."}), 404
            
            habit_data = [{"id": habit.id, "name": habit.name, "completed": habit.completed, "frequency": habit.frequency} for habit in habits]
            return jsonify({"habits": habit_data}), 200

        except Exception as e:
            current_app.logger.error(f"Error fetching habits: {str(e)}")
            return jsonify({"message": "Error fetching habits."}), 500

    # Test MongoDB connection
    @app.route("/test-mongo")
    def test_mongo():
        try:
            mongo.db.list_collection_names()  # Check if connection is working
            return "MongoDB is connected and operational!"
        except Exception as e:
            return f"Error connecting to MongoDB: {str(e)}"

    # Flask HTML Test Page
    @app.route('/test', methods=['GET'])
    def test():
        return jsonify({"message": "Success! Backend is working."})

    app.route('/habits', methods=['GET'])
    def test():
        return jsonify({"message": "Success! Backend is working."})    

    @app.route('/test-page', methods=['GET'])
    def test_page():
        return render_template('test-page.html')

    # Serve React Frontend
    REACT_BUILD_DIR = os.getenv("REACT_BUILD_DIR", "frontend/build")

    @app.route('/')
    def serve_react():
        return send_from_directory(REACT_BUILD_DIR, 'index.html')

    @app.route('/static/<path:path>')
    def serve_static(path):
        return send_from_directory(f"{REACT_BUILD_DIR}/static", path)

    @app.route('/<path:path>')
    def serve_react_app(path):
        # Prevent API calls from being hijacked by frontend serving
        if path.startswith("api/"):
            return jsonify({"message": "API route not found."}), 404
        return send_from_directory(REACT_BUILD_DIR, 'index.html')

    return app

# Create the Flask application instance
app = create_app()

if __name__ == '__main__':
    app.run(debug=True)
